version: '3.7'

services:
  db:
    image: mysql/mysql-server:latest
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db-data:/var/lib/mysql
      - ./backup/staging/db:/var/backup
    restart: unless-stopped
    env_file: .env

  wordpress:
    depends_on:
      - db
    build:
      context: ./wordpress
    image: wheatevo/wordpress:latest
    volumes:
      - wordpress:/var/www/html
      - root:/root
      - ./themes/twentytwenty-wheatevo:/var/www/html/wp-content/themes/twentytwenty-wheatevo
      - ./backup/staging/wordpress:/var/backup
    restart: unless-stopped
    env_file: .env
  
  web:
    depends_on:
      - wordpress
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "${HTTPS_PORT:-8443}:443"
    volumes:
      - wordpress:/var/www/html
      - ./themes/twentytwenty-wheatevo:/var/www/html/wp-content/themes/twentytwenty-wheatevo
      - ${CERT_DIR:-/opt/web/certs}:/etc/nginx/certs
      - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./nginx/conf.d/redirect.conf:/etc/nginx/conf.d/redirect.conf
      - ./nginx/mime.types:/etc/nginx/mime.types

volumes:
    db-data:
    wordpress:
    root:
